server:
  port: 9091
spring:
  application:
    name: billingsystem
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/billing
    username: billing-admin
    password: billing123$$
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        SQL=DEBUG:
      springframework: info
default:
  role: ROLE_DEFAULT
user:
  firstname:
    empty: First Name cannot be empty.
jwt:
  secretkey: secrete
  access-token-expiration: 5000000
  refresh-token-expiration: 10000000